# Generated by Django 5.2.1 on 2025-05-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_badmintonmanager_image_badmintonplayer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('sport', models.CharField(max_length=50)),
                ('is_previous', models.BooleanField(default=False)),
            ],
        ),
    ]
