# Generated by Django 5.2.1 on 2025-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='sport',
            field=models.CharField(choices=[('Badminton', 'Badminton'), ('Cricket', 'Cricket'), ('Football', 'Football')], default='Badminton', max_length=20),
        ),
    ]
